[package]
name = "moatd-ebpf"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"
publish = false

[dependencies]
moatd-common = { path = "../moatd-common", default-features = false }
aya-ebpf = "0.1"
aya-log-ebpf = "0.1"
network-types = "0.0.7"

[build-dependencies]
which = { version = "8", default-features = false, features = ["real-sys"] }

[[bin]]
name = "moatd-bpf"
path = "src/main.rs"
